# Generated by Django 3.2.7 on 2022-01-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('pac_high_score', models.PositiveIntegerField(null=True)),
                ('snake_high_score', models.PositiveIntegerField(null=True)),
                ('run_high_score', models.PositiveIntegerField(null=True)),
                ('flap_high_score', models.PositiveIntegerField(null=True)),
                ('galaga_high_score', models.PositiveIntegerField(null=True)),
                ('numbers_high_score', models.PositiveIntegerField(null=True)),
                ('tetris_high_score', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('user', models.ManyToManyField(to='app.User')),
            ],
        ),
    ]
