# Generated by Django 3.2.7 on 2022-01-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, null=True)),
                ('pac_high_score', models.PositiveIntegerField(null=True)),
                ('snake_high_score', models.PositiveIntegerField(null=True)),
                ('run_high_score', models.PositiveIntegerField(null=True)),
                ('flap_high_score', models.PositiveIntegerField(null=True)),
                ('galaga_high_score', models.PositiveIntegerField(null=True)),
                ('numbers_high_score', models.PositiveIntegerField(null=True)),
                ('tetris_high_score', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user',
            field=models.ManyToManyField(to='app.UserProfile'),
        ),
    ]
