# Generated by Django 3.2.7 on 2022-01-05 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20220104_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pac_high_score', models.PositiveIntegerField(null=True)),
                ('snake_high_score', models.PositiveIntegerField(null=True)),
                ('run_high_score', models.PositiveIntegerField(null=True)),
                ('flap_high_score', models.PositiveIntegerField(null=True)),
                ('galaga_high_score', models.PositiveIntegerField(null=True)),
                ('numbers_high_score', models.PositiveIntegerField(null=True)),
                ('tetris_high_score', models.PositiveIntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='flap_high_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='galaga_high_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='numbers_high_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pac_high_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='run_high_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='snake_high_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tetris_high_score',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
